### PR TITLE
Adding support for persistent_id field

### PR DESCRIPTION
**Pull request by samir-moloco**
Adding support for persistent_id in the JS client.

### CODE REVIEW

**Review by sjhan-moloco — CHANGES_REQUESTED** [review]
We also need to update the data conversion function and related unit tests.
https://github.com/moloco-mcm/event-api-client-js/blob/320f9188909b0c77c50da281b35a78960af8320d/src/v1/events/utils.ts#L3
https://github.com/moloco-mcm/event-api-client-js/blob/main/src/v1/events/__tests__/utils.test.ts

**Comment by samir-moloco** [comment]
Oh yeah missed this one, let me modify this too!

**Comment by samir-moloco** [comment]
@sjhan-moloco should be all good! please review this change, thank you!

**Review by sjhan-moloco — APPROVED** [review]
LGTM

**Pull request merged**
